### PR TITLE
Fix deprecation warning

### PR DESCRIPTION
**Pull request by HakShak**
Deprecation warning removal and compatibility with Python 3

### CODE REVIEW

**Comment by bendemaree** [comment]
Hey @HakShak, thanks for the contribution! Can you give a little more context around your change?

**Comment by HakShak** [comment]
Sure, I'm not a veteran python programmer at all, but it seems that the instantiation trick used here to prime the gcloud credentials is a bit hacky for 2.7 and not accepted at all by 3.5

There is a deprecation warning thrown by 2.7
```DeprecationWarning: super.(RequestsProxy, cls).__new__() takes no parameter```
Which is basically the same as
```DeprecationWarning: object.__new__() takes no parameters```

And in 3.5 this is just a TypeError with the same text

They way the credential priming code was written makes it look like the designer was potentially expecting a class to be injected in the inheritance tree between RequestsProxy and object, but that doesn't seem to happen anywhere. Or from another perspective, it seems they were trying to be explicit about which __new__ was called, but all my testing around this seems to point to this explicit behavior never happening and object.__new__() is always called.

**Comment by Frostykill** [comment]
@HakShak Thanks! This fix works for me using python3.5 and I think it needs to be merged.

**Comment by bendemaree** [comment]
@HakShak @Frostykill so sorry for not getting back to you on this; we have not forgotten you! When you opened the PR we found out that we need to have you sign a CLA...but that doesn't exist quite yet. We are very close and will get back to you as soon as we can.

**Comment by bendemaree** [comment]
@HakShak Would you mind shooting me a quick email at ben.demaree@ave81.com so we can get your CLA all set? TIA!

**Comment by bendemaree** [comment]
@HakShak CLA looks good, and I've published 0.12.1 with the change. Thank you very much!

**Pull request merged**
